services:
    
  web:
    build:
      context: ./frontend/deuxieme-ver
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
    restart:  always
    environment:
      - NODE_ENV=production
      - BACKEND_HOST=oss_backend
    networks:
      - oss-networks


networks:
  oss-networks:
    driver: bridge
