services:
    
  web:
    build:
      context: ./frontend/deuxieme-ver
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
    restart:  always
    environment:
      - NODE_ENV=production
      - BACKEND_HOST=oss_backend
    networks:
      - oss-networks

  oss_backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5058:5058"
    volumes:
      - .:/Backend
    restart:  always
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - oss-networks

networks:
  oss-networks:
    driver: bridge

